version: '3.8'

services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "8000:8000"

  
  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    ports:
      - "8501:8501"