name: TS CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python: '3.10.6'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 . || echo "Lint warnings found"

    - name: Format check with black
      run: |
        pip install black
        black --check . || echo "Some files would be reformatted"

    - name: Type check with pyright
      uses: jakebailey/pyright-action@v1

    
    - name: Run tests
      run: |
        pytest || echo "No tests found, Skipping..."


